# Default values for qtest-launch app.

image:
  repository: qasymphony/launch
  pullPolicy: IfNotPresent
  tag: "1.6.5"

service:
  type: LoadBalancer
  port: 3080
  targetport: 3080
  servicename: qtest-launch-service

qTestLaunch:
  qTestLaunchPostgresUrl: ""
  qTestLaunchRootURL: http://launch.container-dev.qtestdev.com
  qTestLaunchQTestURL: http://qtestdev1.container-dev.qtestdev.com
  qTestLaunchNodeTLSRejectUnAuthorized: "0"
  qTestLaunchTCPWD: "qTest"
  qTestLaunchPort: "3080"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - launch.container-dev.qtestdev.com
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80