apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-insights-etl-resource-quota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.cpu: "3.6"
    requests.memory: 6.8Gi
    pods: "4"
    persistentvolumeclaims: "50"
    requests.storage: "500Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-insights-etl-limit-range
spec:
  limits:
    - max:
        cpu: "1"
        memory: 2Gi
      min:
        cpu: "0.85"
        memory: 0.85Gi
      default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
          cpu: "0.85"
          memory: 0.85Gi
      type: Container
