apiVersion: v1
data:
  qTestInsightsEtlDBPassword: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlDBPassword }}"
  qTestInsightsEtlWriteQTestDBPassword: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlWriteQTestDBPassword }}"
  qTestInsightsEtlSessionDBPassword: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlSessionDBPassword }}"
kind: Secret
metadata:
  name: qtest-insights-etl-secret
type: Opaque
