apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-insights-config
  labels:
    app: qTestInsights
data:
  qTestInsightsProxyEnabled: "{{ .Values.qTestInsights.qTestInsightsProxyEnabled }}"
  qTestInsightsProxyHTTP: "{{ .Values.qTestInsights.qTestInsightsProxyHTTP }}"
  qTestInsightsProxyHTTPS: "{{ .Values.qTestInsights.qTestInsightsProxyHTTPS }}"
  qTestInsightsCatalinaOpts: "{{ .Values.qTestInsights.qTestInsightsCatalinaOpts }}"
  qTestInsightsDBName: "{{ .Values.qTestInsights.qTestInsightsDBName }}"
  qTestInsightsDBHost: "{{ .Values.qTestInsights.qTestInsightsDBHost }}"
  qTestInsightsDBUser: "{{ .Values.qTestInsights.qTestInsightsDBUser }}"
  qTestInsightsWriteQTestDBName: "{{ .Values.qTestInsights.qTestInsightsWriteQTestDBName }}"
  qTestInsightsWriteQTestDBHost: "{{ .Values.qTestInsights.qTestInsightsWriteQTestDBHost }}"
  qTestInsightsWriteQTestDBUser: "{{ .Values.qTestInsights.qTestInsightsWriteQTestDBUser }}"
  qTestInsightsSessionDBName: "{{ .Values.qTestInsights.qTestInsightsSessionDBName }}"
  qTestInsightsSessionDBHost: "{{ .Values.qTestInsights.qTestInsightsSessionDBHost }}"
  qTestInsightsSessionDBUser: "{{ .Values.qTestInsights.qTestInsightsSessionDBUser }}"
  qTestInsightsCSRFAllowPattern: "{{ .Values.qTestInsights.qTestInsightsCSRFAllowPattern }}"