apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-insights-resource-quota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.cpu: "4"
    requests.memory: 8Gi
    pods: "4"
    persistentvolumeclaims: "50"
    requests.storage: "500Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-insights-limit-range
spec:
  limits:
    - max:
        cpu: "1"
        memory: 2Gi
      min:
        cpu: "0.8"
        memory: 1800Mi
      default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
          cpu: "0.8"
          memory: 1800Mi
      type: Container
