apiVersion: v1
data:
  qTestInsightsDBPassword: "{{ .Values.qTestInsights.qTestInsightsDBPassword }}"
  qTestInsightsWriteQTestDBPassword: "{{ .Values.qTestInsights.qTestInsightsWriteQTestDBPassword }}"
  qTestInsightsSessionDBPassword: "{{ .Values.qTestInsights.qTestInsightsSessionDBPassword }}"
kind: Secret
metadata:
  name: qtest-insights-secret
type: Opaque
