# Default values for scenario App.

image:
  repository: qasymphony/scenario
  pullPolicy: IfNotPresent
  tag: "3.3.4"

service:
  type: LoadBalancer
  port: 6080
  targetport: 6080
  servicename: qtest-scenario-service

qTestScenario:
  qTestScenarioDBConnection: ""
  qTestScenarioPort: "6080"
  qTestScenarioLocalBaseURL: http://scenario.container-dev.qtestdev.com
  qTestScenarioNodeTLSRejectUnAuthorized: "0"
  qTestScenarioNodeEnvironment: production
  qTestScenarioRefreshTokenSecret: ""
  qTestScenarioAppKeyDescriptor: ""
  qTestScenarioQTestURL: http://qtestdev1.container-dev.qtestdev.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  canary:
    annotations: {}
  labels: {}
  hosts:
    - scenario.container-dev.qtestdev.com
  paths:
    - /
  extraPaths:
    []
  tls:
    []
  https: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
