apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-pulse-configmap
  labels:
    app: qTestPulse
data:
  qTestPulsePGUrl: "{{ .Values.qTestPulse.qTestPulsePGUrl }}"
  qTestPulseRootURL: "{{ .Values.qTestPulse.qTestPulseRootURL }}"
  qTestPulseQTestURL: "{{ .Values.qTestPulse.qTestPulseQTestURL }}"
  qTestPulseScenarioURL: "{{ .Values.qTestPulse.qTestPulseScenarioURL }}"
  qTestPulseNodeTLSRejectUnAuthorized: "{{ .Values.qTestPulse.qTestPulseNodeTLSRejectUnAuthorized }}"
  qTestPulsePort: "{{ .Values.qTestPulse.qTestPulsePort }}"
  qTestPulseNodeEnv: "{{ .Values.qTestPulse.qTestPulseNodeEnv }}"