apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: qtest-pulse
  template:
    metadata:
      labels:
        app: qtest-pulse
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulseNodeEnv
            - name: PG_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulsePGUrl
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulsePort
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulseNodeTLSRejectUnAuthorized
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulseRootURL
            - name: QTEST_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulseQTestURL
            - name: SCENARIO_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-config
                  key: qTestPulseScenarioURL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
