{{- if .Values.workflow.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argowf-chaos-
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: {{ .Values.workflow.adminModeNamespace }}
spec:
  entrypoint: argowf-chaos
  podGC:  # Pod GC provides the ability to delete pods automatically without deleting the workflow.
    # OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnWorkflowSuccess
  serviceAccountName: argo-chaos
  templates:
    - name: argowf-chaos
      steps:
        - - name: run-benchmark
            template: run-benchmark
          - name: run-chaos
            template: run-chaos
        - - name: revert-chaos
            template: revert-chaos
    - name: run-chaos
      inputs:
        artifacts:
        - name: run-chaos
          path: /tmp/chaosengine.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                name: qtest-mgr-pod-delete-chaos
                namespace: {{ .Values.workflow.adminModeNamespace }}
              spec:
                appinfo:
                  appns: qtest
                  applabel: "app=test-conductor"
                  appkind: rollout
                jobCleanUpPolicy: retain
                monitoring: false
                annotationCheck: 'true'
                engineState: 'active'
                chaosServiceAccount: litmus-admin
                experiments:
                  - name: pod-delete
                    spec:
                      components:
                        env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "30"
                          - name: CHAOS_INTERVAL
                            value: "10"
                          - name: FORCE
                            value: "false"
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['kubectl apply -f /tmp/chaosengine.yaml -n qtest | echo "sleeping for 120s" | sleep 120 ']

    - name: run-benchmark
      inputs:
        artifacts:
        - name: run-benchmark
          path: /tmp/bench.yaml
          raw:
            data: |
              apiVersion: batch/v1
              kind: Job
              metadata:
                labels:
                  app: test-conductor-bench
                generateName: qtest-mgr-bench-
              spec:
                template:
                  metadata:
                    labels:
                      app: test-conductor-bench
                  spec:
                    restartPolicy: Never
                    containers:
                    - args:
                      - -c
                      - /go/bin/main -r -c10 -t${BENCHMARK_DURATION} -n 10000000 http://${qtest-mgr_SVC_NAME}:${qtest-mgr_PORT_NUM}/; exit 0
                      command:
                      - /bin/sh
                      env:
                        - name: qtest-mgr_SVC_NAME
                          value: "test-conductor.default.svc.cluster.local"
                        - name: qtest-mgr_PORT_NUM
                          value: "80"
                        - name: BENCHMARK_DURATION
                          value: "300"
                      image: devth/alpine-bench
                      imagePullPolicy: Always
                      name: test-conductor-bench
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: ['kubectl create -f /tmp/bench.yaml -n qtest']

    - name: revert-chaos
      container:
        image: lachlanevenson/k8s-kubectl
        command: [sh, -c]
        args: [' sleep 20 | kubectl delete chaosengine qtest-mgr-pod-delete-chaos -n {{ .Values.workflow.adminModeNamespace }}']
{{- end }}
