{{- if .Values.deployments.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      initContainers:
      - image: "{{ .Values.image.liquibase }}:{{ .Values.image.liquibasetag | default .Chart.AppVersion }}"
        name: qtestliquibase
        imagePullPolicy: {{ .Values.image.liquibasepullpolicy }}
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: qtest-manager-config
                key: client.jdbc.postgres.url
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: qtest-manager-config
                key: client.jdbc.postgres.username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qtest-manager-secret
      {{- if .Values.imageCredentials.enabled -}}
                key: client.jdbc.postgres.password
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
      - name: {{ .Values.secrets.existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        envFrom:
          - configMapRef:
              name: qtest-manager-config
          - secretRef:
              name: qtest-manager-secret
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      volumes:
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}
