apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-conductor
  template:
    metadata:
      labels:
        app: test-conductor
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        env:
           - name: POSTGRES_USER
             valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
           - name: POSTGRES_PASSWORD
             valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
           - name: POSTGRES_HOST
             valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http               
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      volumes:
      - name: qtest-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}