apiVersion: batch/v1
kind: Job
metadata:
  name: mgr-liquibase-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: mgr-liquibase-job
      labels:
        app: qtest-mgr
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: qtestliquibase
          image: "{{ .Values.image.liquibase }}:{{ .Values.image.liquibasetag }}"
          imagePullPolicy: {{ .Values.image.liquibasepullpolicy }}
          env:
            - name: postgres_url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: client.jdbc.postgres.url
          # envFrom:
          #   - configMapRef:
          #       name: qtest-liquibase-config
          #   - secretRef:
          #       name: qtest-manager-secret
      restartPolicy: OnFailure