#qtest jfrog secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: qtest-jfrog
spec:
  encryptedData:
    .dockerconfigjson: AgBrysNsBP7kW34q82/PLHdEzzZPDsXO+iRcN/Uw3r8nFa47XTYspRgtKOEdYeDNJtKtoCroYMn3TUy0d7dCQtm01tq4WNYt8MqyRZLuSdpzn0Og+OVbpa2CaVo0WhOowSwMs4lt9VUxsNBxP8w+u5PKmJsz85n/KAHRp8a9wAbUFO55EfyPgy7dqcU2fxLPSH27srHLL4XIxvIvjpp/GnL7NGOQ1a+VHu+7hVA7pTvUXOACaalkNmgdth/QQBtGK1a5vw0A7nGcXmJMSSPJoUmcKKI/yzq3FQUTd5ZehReEK3nMcxkUJ4pyfLaSd1HuTO86k+XcDiSAf2xuixRQy8RJx4vHmXlT3JZ3TpIgzAxHkrjAQYXtXEAv6FnD6enfVGHOzoBtDkO/T+YO2oUUUFq7hCES8CeJ4qBmRECHrvPCEb+7nCFdg4oK8NzWiwL/2siJXkxTTU0OFcRzoSkmdRvAzLOpaLBxSOjL3KmkrVRhpG/Zn2EAgJLdtjr5MuoCnzwA0qm53AQFKW4FYribjZchxi/Th+3D+l6gjPi5VeKHee6qLcsIQBdIXkXj/bChzAZbso+uW60T7BYzvoz+b5Q/OpOplyBmWqQU2EFcCsXL3bZG1C9EcBdkj1i864PDPlmShBClky78uukp27IcluaWGHIYRakP50bADxeZ9ubhhxBei9l3fut9vaHzlzzGpuXJeKmrxJhOr6oodNnR4i0Orcpwkn3JMC+rf/R1+tE2A8Oum/Pr5eIPmWRSW56/Nv4Y8xM1N8qhV7eakiDO1BxbhVvorxlKU0CtNi7Rv5t6PCeZS3P6t9/9QPH9mbRF1Wek9ZRzRBL2ME1hQcWYye3u9m++usIyLN1CWNruCdrZEpcsDeOZtxH+MjsadAUT48HIql+/Tfbv+lcYJvzk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: qtest-jfrog
    type: kubernetes.io/dockerconfigjsonc
---
# devqtest.jfrog.io secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: devqtestjfrog
spec:
  encryptedData:
    .dockerconfigjson: AgCcPqKO546BpHD4ix5Dgji0TD/YChNsTQb3RzOdfmXmz9xop1bFqZNHnM+aN5kjx8nCRa9ERdaqOlwImeONJ9ADOeL+4vnLeHWcKtVwqE1rOsu2Kp+y6lc1G7Nr5nO8lD+aa3ZZWHf5WCBRJn6HNgY3SDI5dGF357sXmn8KxqaI7++nxecI5K6sH4QiCnVVtsGz2Cx6pArQDq4Q6WJeWsUTeRdDrzuXLrp595w0pkQD3q7n8oYy+mmz6g8wi4LMJrjLXxoB6DEgpmeB6nJMazeGpKmFXC1FQywbAZ9U6upXPQ9vp15fgUcRcMuSN4fi+R06jyxcM9lY3gSxxuuAUtcENn+crWCrYjybvrliUucHCoerq4jzHLZZvQs90QavL5Br+KcyRDGwGMiMt7pyiLdYTqy9uBfCSP16bdcs/ZGkwftMtajKWbqZlbocbQeJ228H2JdMz0jo+7Jyzp3dh5f8ZbawZneKOf3nYj5/+/DRUpWlet16ZMlNCHiV1CYu/U8xllYjD30/Iu5my25/4X6wOWJxMyx3pGKRKPMiPuF99jaVlE91w5R/k6dka+/lC9YV85x/iQyoXVjtLWlaqZXsmRBVeJpnrGArTAY0HtL4KbABG53Zl7BmajnRKOUEPrLWCHi5hHY3SeBnJs5jYVa3x2Rf34VdjscPYGlUSrm7tH0LNpjMRj42I836T3O1vOL9UBdzUhcj1smPr84J9L1s+ftF7GwmGKagtzaPA7m+M9qT6RygkYFgcNOHr5lGQWH5j9GAa7pdh6MUQQjxNTgZVxaWeAid7YGjv6pZm+XZtH3m6ML79LJFRgtOUyZvwrLTj0jgOOAB3oSbxVPdngOVX5Aha7O/sTGcG5ITzN5O1o8G7CPG9+oTrLdCN/PItPQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: devqtestjfrog
    type: kubernetes.io/dockerconfigjson


