{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  client.jdbc.postgres.password: "{{ .Values.qTestManager.client.jdbc.postgresPassword}}"
  client.jdbc.postgres.readonly.password: "{{ .Values.qTestManager.client.jdbc.postgresReadOnlyPassword}}"
  s3.secretKey: "{{ .Values.qTestManager.s3.SecretKey}}"
  s3.accessKey: "{{ .Values.qTestManager.s3.AccessKey}}"
  mail.password: "{{ .Values.qTestManager.mail.password}}"
kind: Secret
metadata:
  name: qtest-manager-secret
type: Opaque
{{- end }}
{{- if and .Values.imageCredentials.enabled (not .Values.secrets.existingImageCredentials) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
