apiVersion: v1
data:
  qTestMgrClientjdbcPostgresPassword: "{{ .Values.qTestManager.clientJdbc.postgresPassword}}"
  qTestMgrClientjdbcPostgresReadonlyPassword: "{{ .Values.qTestManager.clientJdbc.postgresReadOnlyPassword}}"
  qTestMgrS3SecretKey: "{{ .Values.qTestManager.s3.SecretKey}}"
  qTestMgrS3AccessKey: "{{ .Values.qTestManager.s3.AccessKey}}"
  qTestMgrMailPassword: "{{ .Values.qTestManager.mail.password}}"
kind: Secret
metadata:
  name: qtest-manager-secret
type: Opaque
---
{{- if .Values.imageCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
