apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.servicename }}
  labels:
    app: test-conductor
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-chart.chart" . }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.services.port }}
    targetPort: {{ .Values.services.targetport }}
  selector:
    app: test-conductor
    release: {{ .Release.Name }}
  type: {{ .Values.services.type }}
