apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servicename }}
  labels:
    app: qtest-mgr
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-chart.chart" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  selector:
    app: qtest-mgr
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
