apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.servicename }}
  labels:
    app: test-conductor
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: test-conductor
  type: {{ .Values.service.type }}