name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'Charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          version: v1.1.1 #renovate: datasource=github-releases depName=helm/chart-releaser
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'